#!/bin/sh
# Written by Ricardo F. <rfrail3@yahoo.es>.

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $local_fs $syslog $named $network $time
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Run no-ip service
# Description:       Run no-ip service 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh
. /lib/lsb/init-functions

F_BIN='noip2'
SERVC="/usr/local/bin/$F_BIN"

do_start () {
	# Start service
	if  (pidof $SERVC > /dev/null)   ; then
                log_action_begin_msg "$F_BIN is already running!"
		log_end_msg 1
        else
                log_action_begin_msg "Starting $F_BIN"
                $SERVC
		log_end_msg 0
        fi
}

do_stop () {
	# Stop service
	if  (pidof $SERVC > /dev/null)   ; then
                log_action_begin_msg "Stopping $F_BIN"
		killall $SERVC
		log_end_msg 0
        else
                log_action_begin_msg "$F_BIN was already stopped!"
		log_end_msg 1
        fi
}

do_status () {
	log_action_begin_msg "Status of $F_BIN"
	if  (pidof $SERVC > /dev/null)   ; then
		log_action_end_msg 0 "$F_BIN running"
	else
		log_action_end_msg 1 "$F_BIN stopped"
	fi
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	log_action_begin_msg "Restarting $F_BIN"
	log_end_msg 0
	do_stop
	do_start
	;;
  stop)
	do_stop
	;;
  status|test)
	do_status
	exit $?
	;;
  *)
	echo "Usage: $F_BIN [start|stop|restart|status|test]" >&2
	exit 3
	;;
esac

